services:
  # Banco de Dados MongoDB
  database:
    image: mongo:latest
    container_name: blog_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # API Back-End (Node.js)
  app:
    build: 
      context: ./blog-api-node-docker
      dockerfile: Dockerfile
    container_name: blog_api_node
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/blogdb
      - PORT=3000
    depends_on:
      - database

  # Front-End (React + Vite + Nginx)
  front-end:
    build:
      context: ./tech-challenge-blog-frontend
      dockerfile: Dockerfile
    container_name: blog_frontend_nginx
    restart: always
    ports:
      - "80:80" # Blog abre direto digitando http://localhost no navegador
    depends_on:
      - app # O Front só sobe depois que a API Node estiver de pé

volumes:
  mongo-data: